version = 5.5.0
archive_dir = /etc/letsencrypt/archive/studymation.online
cert = /etc/letsencrypt/live/studymation.online/cert.pem
privkey = /etc/letsencrypt/live/studymation.online/privkey.pem
chain = /etc/letsencrypt/live/studymation.online/chain.pem
fullchain = /etc/letsencrypt/live/studymation.online/fullchain.pem
[renewalparams]
account = 815d2d82c9dd73635d1fa86b2ff75ad3
pref_challs = dns-01,
authenticator = manual
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
